In [21]:
import pandas as pd
doc = pd.read_csv("C:/Users/이재영/OneDrive/바탕 화면/electric_train.csv/electirc_test.csv",encoding='utf-8-sig')

In [22]:
import numpy as np
import pandas as pd

# 시각화 라이브러리
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        
sns.set_style("whitegrid")

In [23]:
train_data = pd.read_csv("C:/Users/이재영/OneDrive/바탕 화면/electric_train.csv/electric_train.csv")
test_data = pd.read_csv("C:/Users/이재영/OneDrive/바탕 화면/electric_train.csv/electirc_test.csv")

In [24]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7593355 entries, 0 to 7593354
Data columns (total 17 columns):
 #   Column                      Dtype
---  ------                      -----
 0   Unnamed: 0                  int64
 1   electric_train.num          int64
 2   electric_train.tm           object
 3   electric_train.hh24         int64
 4   electric_train.n            int64
 5   electric_train.stn          int64
 6   electric_train.sum_qctr     int64
 7   electric_train.sum_load     float64
 8   electric_train.n_mean_load  float64
 9   electric_train.nph_ta       float64
 10  electric_train.nph_hm       float64
 11  electric_train.nph_ws_10m   float64
 12  electric_train.nph_rn_60m   float64
 13  electric_train.nph_ta_chi   float64
 14  electric_train.weekday      int64
 15  electric_train.week_name    int64
 16  electric_train.elec         float64
dtypes: float64(8), int64(8), object(1)
memory usage: 984.9+ MB

In [25]:
train_data.describe()

,Unnamed: 0,electric_train.num,electric_train.hh24,electric_train.n,electric_train.stn,electric_train.sum_qctr,electric_train.sum_load,electric_train.n_mean_load,electric_train.nph_ta,electric_train.nph_hm,electric_train.nph_ws_10m,electric_train.nph_rn_60m,electric_train.nph_ta_chi,electric_train.weekday,electric_train.week_name,electric_train.elec
count,7.593355e+06,7.593355e+06,7.593355e+06,7.593355e+06,7.593355e+06,7.593355e+06,7.593355e+06,7.593355e+06,7.593355e+06,7.593355e+06,7.593355e+06,7.593355e+06,7.593355e+06,7.593355e+06,7.593355e+06,7.593355e+06
mean,3.796678e+06,1.542260e+04,1.250000e+01,4.189762e+01,4.977980e+02,6.243189e+04,9.408222e+03,2.445487e+02,1.411757e+01,6.997073e+01,1.912586e+00,1.157334e-01,1.375894e+01,3.001837e+00,2.855444e-01,9.999961e+01
std,2.192013e+06,3.312737e+03,6.922185e+00,4.242576e+01,2.564308e+02,5.673208e+04,8.736332e+03,9.149680e+01,8.940662e+00,2.053913e+01,1.755351e+00,9.988575e-01,1.143277e+01,1.997703e+00,4.516734e-01,2.512031e+01
min,1.000000e+00,4.821000e+03,1.000000e+00,1.000000e+01,9.800000e+01,5.475000e+03,3.720400e+02,3.965180e+01,-2.460000e+01,2.700000e+00,-9.900000e+01,0.000000e+00,-2.670000e+01,0.000000e+00,0.000000e+00,-9.900000e+01
25%,1.898340e+06,1.246900e+04,7.000000e+00,1.500000e+01,2.790000e+02,2.340000e+04,3.462960e+03,1.798686e+02,7.400000e+00,5.600000e+01,7.000000e-01,0.000000e+00,4.700000e+00,1.000000e+00,0.000000e+00,8.222000e+01
50%,3.796678e+06,1.616000e+04,1.200000e+01,2.600000e+01,4.940000e+02,4.290000e+04,6.383600e+03,2.329593e+02,1.480000e+01,7.290000e+01,1.500000e+00,0.000000e+00,1.480000e+01,3.000000e+00,0.000000e+00,9.570000e+01
75%,5.695016e+06,1.839200e+04,1.800000e+01,5.200000e+01,6.730000e+02,8.130000e+04,1.240928e+04,2.961240e+02,2.150000e+01,8.740000e+01,2.700000e+00,0.000000e+00,2.370000e+01,5.000000e+00,1.000000e+00,1.146400e+02
max,7.593355e+06,2.094700e+04,2.400000e+01,3.070000e+02,9.910000e+02,3.230780e+05,1.107742e+05,6.068307e+02,3.690000e+01,1.000000e+02,2.740000e+01,1.022000e+02,3.740000e+01,6.000000e+00,1.000000e+00,3.730600e+02

In [26]:
train_data.describe(include='O')

          electric_train.tm
count               7593355
unique                26304
top     2020-07-02 01:00:00
freq                    300

In [27]:
for col in train_data.columns:
    if train_data[col].dtype == 'object':
        categories = train_data[col].unique()
        print(f'[{col}] ({len(categories)})')
        print('\n'.join(categories))
        print()

[electric_train.tm] (26304)
2021-01-01 01:00:00
2021-01-01 02:00:00
2021-01-01 03:00:00
2021-01-01 04:00:00
2021-01-01 05:00:00
2021-01-01 06:00:00
2021-01-01 07:00:00
2021-01-01 08:00:00
2021-01-01 09:00:00
2021-01-01 10:00:00
2021-01-01 11:00:00
2021-01-01 12:00:00
2021-01-01 13:00:00
2021-01-01 14:00:00
2021-01-01 15:00:00
2021-01-01 16:00:00
2021-01-01 17:00:00
2021-01-01 18:00:00
2021-01-01 19:00:00
2021-01-01 20:00:00
2021-01-01 21:00:00
2021-01-01 22:00:00
2021-01-01 23:00:00
2021-01-02 00:00:00
2021-01-02 01:00:00
2021-01-02 02:00:00
2021-01-02 03:00:00
2021-01-02 04:00:00
2021-01-02 05:00:00
2021-01-02 06:00:00
2021-01-02 07:00:00
2021-01-02 08:00:00
2021-01-02 09:00:00
2021-01-02 10:00:00
2021-01-02 11:00:00
2021-01-02 12:00:00
2021-01-02 13:00:00
2021-01-02 14:00:00
2021-01-02 15:00:00
2021-01-02 16:00:00
2021-01-02 17:00:00
2021-01-02 18:00:00
2021-01-02 19:00:00
2021-01-02 20:00:00
2021-01-02 21:00:00
2021-01-02 22:00:00
2021-01-02 23:00:00
2021-01-03 00:00:00
2021-01-03 01:00:00
2021-01-03 02:00:00
2021-01-03 03:00:00
2021-01-03 04:00:00
2021-01-03 05:00:00
2021-01-03 06:00:00
2021-01-03 07:00:00
2021-01-03 08:00:00
2021-01-03 09:00:00
2021-01-03 10:00:00
2021-01-03 11:00:00
2021-01-03 12:00:00
2021-01-03 13:00:00
2021-01-03 14:00:00
2021-01-03 15:00:00
2021-01-03 16:00:00
2021-01-03 17:00:00
2021-01-03 18:00:00
2021-01-03 19:00:00
2021-01-03 20:00:00
2021-01-03 21:00:00
2021-01-03 22:00:00
2021-01-03 23:00:00
2021-01-04 00:00:00
2021-01-04 01:00:00
2021-01-04 02:00:00
2021-01-04 03:00:00
2021-01-04 04:00:00
2021-01-04 05:00:00
2021-01-04 06:00:00
2021-01-04 07:00:00
2021-01-04 08:00:00
2021-01-04 09:00:00
2021-01-04 10:00:00
2021-01-04 11:00:00
2021-01-04 12:00:00
2021-01-04 13:00:00
2021-01-04 14:00:00
2021-01-04 15:00:00
2021-01-04 16:00:00
2021-01-04 17:00:00
2021-01-04 18:00:00
2021-01-04 19:00:00
2021-01-04 20:00:00
2021-01-04 21:00:00
2021-01-04 22:00:00
2021-01-04 23:00:00
2021-01-05 00:00:00
2021-01-05 01:00:00
2021-01-05 02:00:00
2021-01-05 03:00:00
2021-01-05 04:00:00
2021-01-05 05:00:00
2021-01-05 06:00:00
2021-01-05 07:00:00
2021-01-05 08:00:00
2021-01-05 09:00:00
2021-01-05 10:00:00
2021-01-05 11:00:00
2021-01-05 12:00:00
2021-01-05 13:00:00
2021-01-05 14:00:00
2021-01-05 15:00:00
2021-01-05 16:00:00
2021-01-05 17:00:00
2021-01-05 18:00:00
2021-01-05 19:00:00
2021-01-05 20:00:00
2021-01-05 21:00:00
2021-01-05 22:00:00
2021-01-05 23:00:00
2021-01-06 00:00:00
2021-01-06 01:00:00
2021-01-06 02:00:00
2021-01-06 03:00:00
2021-01-06 04:00:00
2021-01-06 05:00:00
2021-01-06 06:00:00
2021-01-06 07:00:00
2021-01-06 08:00:00
2021-01-06 09:00:00
2021-01-06 10:00:00
2021-01-06 11:00:00
2021-01-06 12:00:00
2021-01-06 13:00:00
2021-01-06 14:00:00
2021-01-06 15:00:00
2021-01-06 16:00:00
2021-01-06 17:00:00
2021-01-06 18:00:00
2021-01-06 19:00:00
2021-01-06 20:00:00
2021-01-06 21:00:00
2021-01-06 22:00:00
2021-01-06 23:00:00
2021-01-07 00:00:00
2021-01-07 01:00:00
2021-01-07 02:00:00
2021-01-07 03:00:00
2021-01-07 04:00:00
2021-01-07 05:00:00
2021-01-07 06:00:00
2021-01-07 07:00:00
2021-01-07 08:00:00
2021-01-07 09:00:00
2021-01-07 10:00:00
2021-01-07 11:00:00
2021-01-07 12:00:00
2021-01-07 13:00:00
2021-01-07 14:00:00
2021-01-07 15:00:00
2021-01-07 16:00:00
2021-01-07 17:00:00
2021-01-07 18:00:00
2021-01-07 19:00:00
2021-01-07 20:00:00
2021-01-07 21:00:00
2021-01-07 22:00:00
2021-01-07 23:00:00
2021-01-08 00:00:00
2021-01-08 01:00:00
2021-01-08 02:00:00
2021-01-08 03:00:00
2021-01-08 04:00:00
2021-01-08 05:00:00
2021-01-08 06:00:00
2021-01-08 07:00:00
2021-01-08 08:00:00
2021-01-08 09:00:00
2021-01-08 10:00:00
2021-01-08 11:00:00
2021-01-08 12:00:00
2021-01-08 13:00:00
2021-01-08 14:00:00
2021-01-08 15:00:00
2021-01-08 16:00:00
2021-01-08 17:00:00
2021-01-08 18:00:00
2021-01-08 19:00:00
2021-01-08 20:00:00
2021-01-08 21:00:00
2021-01-08 22:00:00
2021-01-08 23:00:00
2021-01-09 00:00:00
2021-01-09 01:00:00
2021-01-09 02:00:00
2021-01-09 03:00:00
2021-01-09 04:00:00
2021-01-09 05:00:00
2021-01-09 06:00:00
2021-01-09 07:00:00
2021-01-09 08:00:00
2021-01-09 09:00:00
2021-01-09 10:00:00
2021-01-09 11:00:00
2021-01-09 12:00:00
2021-01-09 13:00:00
2021-01-09 14:00:00
2021-01-09 15:00:00
2021-01-09 16:00:00
2021-01-09 17:00:00
2021-01-09 18:00:00
2021-01-09 19:00:00
2021-01-09 20:00:00
2021-01-09 21:00:00
2021-01-09 22:00:00
2021-01-09 23:00:00
2021-01-10 00:00:00
2021-01-10 01:00:00
2021-01-10 02:00:00
2021-01-10 03:00:00
2021-01-10 04:00:00
2021-01-10 05:00:00
2021-01-10 06:00:00
2021-01-10 07:00:00
2021-01-10 08:00:00
2021-01-10 09:00:00
2021-01-10 10:00:00
2021-01-10 11:00:00
2021-01-10 12:00:00
2021-01-10 13:00:00
2021-01-10 14:00:00
2021-01-10 15:00:00
2021-01-10 16:00:00
2021-01-10 17:00:00
2021-01-10 18:00:00
2021-01-10 19:00:00
2021-01-10 20:00:00
2021-01-10 21:00:00
2021-01-10 22:00:00
2021-01-10 23:00:00
2021-01-11 00:00:00
2021-01-11 01:00:00
2021-01-11 02:00:00
2021-01-11 03:00:00
2021-01-11 04:00:00
2021-01-11 05:00:00
2021-01-11 06:00:00
2021-01-11 07:00:00
2021-01-11 08:00:00
2021-01-11 09:00:00
2021-01-11 10:00:00
2021-01-11 11:00:00
2021-01-11 12:00:00
2021-01-11 13:00:00
2021-01-11 14:00:00
2021-01-11 15:00:00
2021-01-11 16:00:00
2021-01-11 17:00:00
2021-01-11 18:00:00
2021-01-11 19:00:00
2021-01-11 20:00:00
2021-01-11 21:00:00
2021-01-11 22:00:00
2021-01-11 23:00:00
2021-01-12 00:00:00
2021-01-12 01:00:00
2021-01-12 02:00:00
2021-01-12 03:00:00
2021-01-12 04:00:00
2021-01-12 05:00:00
2021-01-12 06:00:00
2021-01-12 07:00:00
2021-01-12 08:00:00
2021-01-12 09:00:00
2021-01-12 10:00:00
2021-01-12 11:00:00
2021-01-12 12:00:00
2021-01-12 13:00:00
2021-01-12 14:00:00
2021-01-12 15:00:00
2021-01-12 16:00:00
2021-01-12 17:00:00
2021-01-12 18:00:00
2021-01-12 19:00:00
2021-01-12 20:00:00
2021-01-12 21:00:00
2021-01-12 22:00:00
2021-01-12 23:00:00
2021-01-13 00:00:00
2021-01-13 01:00:00
2021-01-13 02:00:00
2021-01-13 03:00:00
2021-01-13 04:00:00
2021-01-13 05:00:00
2021-01-13 06:00:00
2021-01-13 07:00:00
2021-01-13 08:00:00
2021-01-13 09:00:00
2021-01-13 10:00:00
2021-01-13 11:00:00
2021-01-13 12:00:00
2021-01-13 13:00:00
2021-01-13 14:00:00
2021-01-13 15:00:00
2021-01-13 16:00:00
2021-01-13 17:00:00
2021-01-13 18:00:00
2021-01-13 19:00:00
2021-01-13 20:00:00
2021-01-13 21:00:00
2021-01-13 22:00:00
2021-01-13 23:00:00
2021-01-14 00:00:00
2021-01-14 01:00:00
2021-01-14 02:00:00
2021-01-14 03:00:00
2021-01-14 04:00:00
2021-01-14 05:00:00
2021-01-14 06:00:00
2021-01-14 07:00:00
2021-01-14 08:00:00
2021-01-14 09:00:00
2021-01-14 10:00:00
2021-01-14 11:00:00
2021-01-14 12:00:00
2021-01-14 13:00:00
2021-01-14 14:00:00
2021-01-14 15:00:00
2021-01-14 16:00:00
2021-01-14 17:00:00
2021-01-14 18:00:00
2021-01-14 19:00:00
2021-01-14 20:00:00
2021-01-14 21:00:00
2021-01-14 22:00:00
2021-01-14 23:00:00
2021-01-15 00:00:00
2021-01-15 01:00:00
2021-01-15 02:00:00
2021-01-15 03:00:00
2021-01-15 04:00:00
2021-01-15 05:00:00
2021-01-15 06:00:00
2021-01-15 07:00:00
2021-01-15 08:00:00
2021-01-15 09:00:00
2021-01-15 10:00:00
2021-01-15 11:00:00
2021-01-15 12:00:00
2021-01-15 13:00:00
2021-01-15 14:00:00
2021-01-15 15:00:00
2021-01-15 16:00:00
2021-01-15 17:00:00
2021-01-15 18:00:00
2021-01-15 19:00:00
2021-01-15 20:00:00
2021-01-15 21:00:00
2021-01-15 22:00:00
2021-01-15 23:00:00
2021-01-16 00:00:00
2021-01-16 01:00:00
2021-01-16 02:00:00
2021-01-16 03:00:00
2021-01-16 04:00:00
2021-01-16 05:00:00
2021-01-16 06:00:00
2021-01-16 07:00:00
2021-01-16 08:00:00
2021-01-16 09:00:00
2021-01-16 10:00:00
2021-01-16 11:00:00
2021-01-16 12:00:00
2021-01-16 13:00:00
2021-01-16 14:00:00
2021-01-16 15:00:00
2021-01-16 16:00:00
2021-01-16 17:00:00
2021-01-16 18:00:00
2021-01-16 19:00:00
2021-01-16 20:00:00
2021-01-16 21:00:00
2021-01-16 22:00:00
2021-01-16 23:00:00
2021-01-17 00:00:00
2021-01-17 01:00:00
2021-01-17 02:00:00
2021-01-17 03:00:00
2021-01-17 04:00:00
2021-01-17 05:00:00
2021-01-17 06:00:00
2021-01-17 07:00:00
2021-01-17 08:00:00
2021-01-17 09:00:00
2021-01-17 10:00:00
2021-01-17 11:00:00
2021-01-17 12:00:00
2021-01-17 13:00:00
2021-01-17 14:00:00
2021-01-17 15:00:00
2021-01-17 16:00:00
2021-01-17 17:00:00
2021-01-17 18:00:00
2021-01-17 19:00:00
2021-01-17 20:00:00
2021-01-17 21:00:00
2021-01-17 22:00:00
2021-01-17 23:00:00
2021-01-18 00:00:00
2021-01-18 01:00:00
2021-01-18 02:00:00
2021-01-18 03:00:00
2021-01-18 04:00:00
2021-01-18 05:00:00
2021-01-18 06:00:00
2021-01-18 07:00:00
2021-01-18 08:00:00
2021-01-18 09:00:00
2021-01-18 10:00:00
2021-01-18 11:00:00
2021-01-18 12:00:00
2021-01-18 13:00:00
2021-01-18 14:00:00
2021-01-18 15:00:00
2021-01-18 16:00:00
2021-01-18 17:00:00
2021-01-18 18:00:00
2021-01-18 19:00:00
2021-01-18 20:00:00
2021-01-18 21:00:00
2021-01-18 22:00:00
2021-01-18 23:00:00
2021-01-19 00:00:00
2021-01-19 01:00:00
2021-01-19 02:00:00
2021-01-19 03:00:00
2021-01-19 04:00:00
2021-01-19 05:00:00
2021-01-19 06:00:00
2021-01-19 07:00:00
2021-01-19 08:00:00
2021-01-19 09:00:00
2021-01-19 10:00:00
2021-01-19 11:00:00
2021-01-19 12:00:00
2021-01-19 13:00:00
2021-01-19 14:00:00
2021-01-19 15:00:00
2021-01-19 16:00:00
2021-01-19 17:00:00
2021-01-19 18:00:00
2021-01-19 19:00:00
2021-01-19 20:00:00
2021-01-19 21:00:00
2021-01-19 22:00:00
2021-01-19 23:00:00
2021-01-20 00:00:00
2021-01-20 01:00:00
2021-01-20 02:00:00
2021-01-20 03:00:00
2021-01-20 04:00:00
2021-01-20 05:00:00
2021-01-20 06:00:00
2021-01-20 07:00:00
2021-01-20 08:00:00
2021-01-20 09:00:00
2021-01-20 10:00:00
2021-01-20 11:00:00
2021-01-20 12:00:00
2021-01-20 13:00:00
2021-01-20 14:00:00
2021-01-20 15:00:00
2021-01-20 16:00:00
2021-01-20 17:00:00
2021-01-20 18:00:00
2021-01-20 19:00:00
2021-01-20 20:00:00
2021-01-20 21:00:00
2021-01-20 22:00:00
2021-01-20 23:00:00
2021-01-21 00:00:00
2021-01-21 01:00:00
2021-01-21 02:00:00
2021-01-21 03:00:00
2021-01-21 04:00:00
2021-01-21 05:00:00
2021-01-21 06:00:00
2021-01-21 07:00:00
2021-01-21 08:00:00
2021-01-21 09:00:00
2021-01-21 10:00:00
2021-01-21 11:00:00
2021-01-21 12:00:00
2021-01-21 13:00:00
2021-01-21 14:00:00
2021-01-21 15:00:00
2021-01-21 16:00:00
2021-01-21 17:00:00
2021-01-21 18:00:00
2021-01-21 19:00:00
2021-01-21 20:00:00
2021-01-21 21:00:00
2021-01-21 22:00:00
2021-01-21 23:00:00
2021-01-22 00:00:00
2021-01-22 01:00:00
2021-01-22 02:00:00
2021-01-22 03:00:00
2021-01-22 04:00:00
2021-01-22 05:00:00
2021-01-22 06:00:00
2021-01-22 07:00:00
2021-01-22 08:00:00
2021-01-22 09:00:00
2021-01-22 10:00:00
2021-01-22 11:00:00
2021-01-22 12:00:00
2021-01-22 13:00:00
2021-01-22 14:00:00
2021-01-22 15:00:00
2021-01-22 16:00:00
2021-01-22 17:00:00
2021-01-22 18:00:00
2021-01-22 19:00:00
2021-01-22 20:00:00
2021-01-22 21:00:00
2021-01-22 22:00:00
2021-01-22 23:00:00
2021-01-23 00:00:00
2021-01-23 01:00:00
2021-01-23 02:00:00
2021-01-23 03:00:00
2021-01-23 04:00:00
2021-01-23 05:00:00
2021-01-23 06:00:00
2021-01-23 07:00:00
2021-01-23 08:00:00
2021-01-23 09:00:00
2021-01-23 10:00:00
2021-01-23 11:00:00
2021-01-23 12:00:00
2021-01-23 13:00:00
2021-01-23 14:00:00
2021-01-23 15:00:00
2021-01-23 16:00:00
2021-01-23 17:00:00
2021-01-23 18:00:00
2021-01-23 19:00:00
2021-01-23 20:00:00
2021-01-23 21:00:00
2021-01-23 22:00:00
2021-01-23 23:00:00
2021-01-24 00:00:00
2021-01-24 01:00:00
2021-01-24 02:00:00
2021-01-24 03:00:00
2021-01-24 04:00:00
2021-01-24 05:00:00
2021-01-24 06:00:00
2021-01-24 07:00:00
2021-01-24 08:00:00
2021-01-24 09:00:00
2021-01-24 10:00:00
2021-01-24 11:00:00
2021-01-24 12:00:00
2021-01-24 13:00:00
2021-01-24 14:00:00
2021-01-24 15:00:00
2021-01-24 16:00:00
2021-01-24 17:00:00
2021-01-24 18:00:00
2021-01-24 19:00:00
2021-01-24 20:00:00
2021-01-24 21:00:00
2021-01-24 22:00:00
2021-01-24 23:00:00
2021-01-25 00:00:00
2021-01-25 01:00:00
2021-01-25 02:00:00
2021-01-25 03:00:00
2021-01-25 04:00:00
2021-01-25 05:00:00
2021-01-25 06:00:00
2021-01-25 07:00:00
2021-01-25 08:00:00
2021-01-25 09:00:00
2021-01-25 10:00:00
2021-01-25 11:00:00
2021-01-25 12:00:00
2021-01-25 13:00:00
2021-01-25 14:00:00
2021-01-25 15:00:00
2021-01-25 16:00:00
2021-01-25 17:00:00
2021-01-25 18:00:00
2021-01-25 19:00:00
2021-01-25 20:00:00
2021-01-25 21:00:00
2021-01-25 22:00:00
2021-01-25 23:00:00
2021-01-26 00:00:00
2021-01-26 01:00:00
2021-01-26 02:00:00
2021-01-26 03:00:00
2021-01-26 04:00:00
2021-01-26 05:00:00
2021-01-26 06:00:00
2021-01-26 07:00:00
2021-01-26 08:00:00
2021-01-26 09:00:00
2021-01-26 10:00:00
2021-01-26 11:00:00
2021-01-26 12:00:00
2021-01-26 13:00:00
2021-01-26 14:00:00
2021-01-26 15:00:00
2021-01-26 16:00:00
2021-01-26 17:00:00
2021-01-26 18:00:00
2021-01-26 19:00:00
2021-01-26 20:00:00
2021-01-26 21:00:00
2021-01-26 22:00:00
2021-01-26 23:00:00
2021-01-27 00:00:00
2021-01-27 01:00:00
2021-01-27 02:00:00
2021-01-27 03:00:00
2021-01-27 04:00:00
2021-01-27 05:00:00
2021-01-27 06:00:00
2021-01-27 07:00:00
2021-01-27 08:00:00
2021-01-27 09:00:00
2021-01-27 10:00:00
2021-01-27 11:00:00
2021-01-27 12:00:00
2021-01-27 13:00:00
2021-01-27 14:00:00
2021-01-27 15:00:00
2021-01-27 16:00:00
2021-01-27 17:00:00
2021-01-27 18:00:00
2021-01-27 19:00:00
2021-01-27 20:00:00
2021-01-27 21:00:00
2021-01-27 22:00:00
2021-01-27 23:00:00
2021-01-28 00:00:00
2021-01-28 01:00:00
2021-01-28 02:00:00
2021-01-28 03:00:00
2021-01-28 04:00:00
2021-01-28 05:00:00
2021-01-28 06:00:00
2021-01-28 07:00:00
2021-01-28 08:00:00
2021-01-28 09:00:00
2021-01-28 10:00:00
2021-01-28 11:00:00
2021-01-28 12:00:00
2021-01-28 13:00:00
2021-01-28 14:00:00
2021-01-28 15:00:00
2021-01-28 16:00:00
2021-01-28 17:00:00
2021-01-28 18:00:00
2021-01-28 19:00:00
2021-01-28 20:00:00
2021-01-28 21:00:00
2021-01-28 22:00:00
2021-01-28 23:00:00
2021-01-29 00:00:00
2021-01-29 01:00:00
2021-01-29 02:00:00
2021-01-29 03:00:00
2021-01-29 04:00:00
2021-01-29 05:00:00
2021-01-29 06:00:00
2021-01-29 07:00:00
2021-01-29 08:00:00
2021-01-29 09:00:00
2021-01-29 10:00:00
2021-01-29 11:00:00
2021-01-29 12:00:00
2021-01-29 13:00:00
2021-01-29 14:00:00
2021-01-29 15:00:00
2021-01-29 16:00:00
2021-01-29 17:00:00
2021-01-29 18:00:00
2021-01-29 19:00:00
2021-01-29 20:00:00
2021-01-29 21:00:00
2021-01-29 22:00:00
2021-01-29 23:00:00
2021-01-30 00:00:00
2021-01-30 01:00:00
2021-01-30 02:00:00
2021-01-30 03:00:00
2021-01-30 04:00:00
2021-01-30 05:00:00
2021-01-30 06:00:00
2021-01-30 07:00:00
2021-01-30 08:00:00
2021-01-30 09:00:00
2021-01-30 10:00:00
2021-01-30 11:00:00
2021-01-30 12:00:00
2021-01-30 13:00:00
2021-01-30 14:00:00
2021-01-30 15:00:00
2021-01-30 16:00:00
2021-01-30 17:00:00
2021-01-30 18:00:00
2021-01-30 19:00:00
2021-01-30 20:00:00
2021-01-30 21:00:00
2021-01-30 22:00:00
2021-01-30 23:00:00
2021-01-31 00:00:00
2021-01-31 01:00:00
2021-01-31 02:00:00
2021-01-31 03:00:00
2021-01-31 04:00:00
2021-01-31 05:00:00
2021-01-31 06:00:00
2021-01-31 07:00:00
2021-01-31 08:00:00
2021-01-31 09:00:00
2021-01-31 10:00:00
2021-01-31 11:00:00
2021-01-31 12:00:00
2021-01-31 13:00:00
2021-01-31 14:00:00
2021-01-31 15:00:00
2021-01-31 16:00:00
2021-01-31 17:00:00
2021-01-31 18:00:00
2021-01-31 19:00:00
2021-01-31 20:00:00
2021-01-31 21:00:00
2021-01-31 22:00:00
2021-01-31 23:00:00
2021-02-01 00:00:00
2021-02-01 01:00:00
2021-02-01 02:00:00
2021-02-01 03:00:00
2021-02-01 04:00:00
2021-02-01 05:00:00
2021-02-01 06:00:00
2021-02-01 07:00:00
2021-02-01 08:00:00
2021-02-01 09:00:00
2021-02-01 10:00:00
2021-02-01 11:00:00
2021-02-01 12:00:00
2021-02-01 13:00:00
2021-02-01 14:00:00
2021-02-01 15:00:00
2021-02-01 16:00:00
2021-02-01 17:00:00
2021-02-01 18:00:00
2021-02-01 19:00:00
2021-02-01 20:00:00
2021-02-01 21:00:00
2021-02-01 22:00:00
2021-02-01 23:00:00
2021-02-02 00:00:00
2021-02-02 01:00:00
2021-02-02 02:00:00
2021-02-02 03:00:00
2021-02-02 04:00:00
2021-02-02 05:00:00
2021-02-02 06:00:00
2021-02-02 07:00:00
2021-02-02 08:00:00
2021-02-02 09:00:00
2021-02-02 10:00:00
2021-02-02 11:00:00
2021-02-02 12:00:00
2021-02-02 13:00:00
2021-02-02 14:00:00
2021-02-02 15:00:00
2021-02-02 16:00:00
2021-02-02 17:00:00
2021-02-02 18:00:00
2021-02-02 19:00:00
2021-02-02 20:00:00
2021-02-02 21:00:00
2021-02-02 22:00:00
2021-02-02 23:00:00
2021-02-03 00:00:00
2021-02-03 01:00:00
2021-02-03 02:00:00
2021-02-03 03:00:00
2021-02-03 04:00:00
2021-02-03 05:00:00
2021-02-03 06:00:00
2021-02-03 07:00:00
2021-02-03 08:00:00
2021-02-03 09:00:00
2021-02-03 10:00:00
2021-02-03 11:00:00
2021-02-03 12:00:00
2021-02-03 13:00:00
2021-02-03 14:00:00
2021-02-03 15:00:00
2021-02-03 16:00:00
2021-02-03 17:00:00
2021-02-03 18:00:00
2021-02-03 19:00:00
2021-02-03 20:00:00
2021-02-03 21:00:00
2021-02-03 22:00:00
2021-02-03 23:00:00
2021-02-04 00:00:00
2021-02-04 01:00:00
2021-02-04 02:00:00
2021-02-04 03:00:00
2021-02-04 04:00:00
2021-02-04 05:00:00
2021-02-04 06:00:00
2021-02-04 07:00:00
2021-02-04 08:00:00
2021-02-04 09:00:00
2021-02-04 10:00:00
2021-02-04 11:00:00
2021-02-04 12:00:00
2021-02-04 13:00:00
2021-02-04 14:00:00
2021-02-04 15:00:00
2021-02-04 16:00:00
2021-02-04 17:00:00
2021-02-04 18:00:00
2021-02-04 19:00:00
2021-02-04 20:00:00
2021-02-04 21:00:00
2021-02-04 22:00:00
2021-02-04 23:00:00
2021-02-05 00:00:00
2021-02-05 01:00:00
2021-02-05 02:00:00
2021-02-05 03:00:00
2021-02-05 04:00:00
2021-02-05 05:00:00
2021-02-05 06:00:00
2021-02-05 07:00:00
2021-02-05 08:00:00
2021-02-05 09:00:00
2021-02-05 10:00:00
2021-02-05 11:00:00
2021-02-05 12:00:00
2021-02-05 13:00:00
2021-02-05 14:00:00
2021-02-05 15:00:00
2021-02-05 16:00:00
2021-02-05 17:00:00
2021-02-05 18:00:00
2021-02-05 19:00:00
2021-02-05 20:00:00
2021-02-05 21:00:00
2021-02-05 22:00:00
2021-02-05 23:00:00
2021-02-06 00:00:00
2021-02-06 01:00:00
2021-02-06 02:00:00
2021-02-06 03:00:00
2021-02-06 04:00:00
2021-02-06 05:00:00
2021-02-06 06:00:00
2021-02-06 07:00:00
2021-02-06 08:00:00
2021-02-06 09:00:00
2021-02-06 10:00:00
2021-02-06 11:00:00
2021-02-06 12:00:00
2021-02-06 13:00:00
2021-02-06 14:00:00
2021-02-06 15:00:00
2021-02-06 16:00:00
2021-02-06 17:00:00
2021-02-06 18:00:00
2021-02-06 19:00:00
2021-02-06 20:00:00
2021-02-06 21:00:00
2021-02-06 22:00:00
2021-02-06 23:00:00
2021-02-07 00:00:00
2021-02-07 01:00:00
2021-02-07 02:00:00
2021-02-07 03:00:00
2021-02-07 04:00:00
2021-02-07 05:00:00
2021-02-07 06:00:00
2021-02-07 07:00:00
2021-02-07 08:00:00
2021-02-07 09:00:00
2021-02-07 10:00:00
2021-02-07 11:00:00
2021-02-07 12:00:00
2021-02-07 13:00:00
2021-02-07 14:00:00
2021-02-07 15:00:00
2021-02-07 16:00:00
2021-02-07 17:00:00
2021-02-07 18:00:00
2021-02-07 19:00:00
2021-02-07 20:00:00
2021-02-07 21:00:00
2021-02-07 22:00:00
2021-02-07 23:00:00
2021-02-08 00:00:00
2021-02-08 01:00:00
2021-02-08 02:00:00
2021-02-08 03:00:00
2021-02-08 04:00:00
2021-02-08 05:00:00
2021-02-08 06:00:00
2021-02-08 07:00:00
2021-02-08 08:00:00
2021-02-08 09:00:00
2021-02-08 10:00:00
2021-02-08 11:00:00
2021-02-08 12:00:00
2021-02-08 13:00:00
2021-02-08 14:00:00
2021-02-08 15:00:00
2021-02-08 16:00:00
2021-02-08 17:00:00
2021-02-08 18:00:00
2021-02-08 19:00:00
2021-02-08 20:00:00
2021-02-08 21:00:00
2021-02-08 22:00:00
2021-02-08 23:00:00
2021-02-09 00:00:00
2021-02-09 01:00:00
2021-02-09 02:00:00
2021-02-09 03:00:00
2021-02-09 04:00:00
2021-02-09 05:00:00
2021-02-09 06:00:00
2021-02-09 07:00:00
2021-02-09 08:00:00
2021-02-09 09:00:00
2021-02-09 10:00:00
2021-02-09 11:00:00
2021-02-09 12:00:00
2021-02-09 13:00:00
2021-02-09 14:00:00
2021-02-09 15:00:00
2021-02-09 16:00:00
2021-02-09 17:00:00
2021-02-09 18:00:00
2021-02-09 19:00:00
2021-02-09 20:00:00
2021-02-09 21:00:00
2021-02-09 22:00:00
2021-02-09 23:00:00
2021-02-10 00:00:00
2021-02-10 01:00:00
2021-02-10 02:00:00
2021-02-10 03:00:00
2021-02-10 04:00:00
2021-02-10 05:00:00
2021-02-10 06:00:00
2021-02-10 07:00:00
2021-02-10 08:00:00
2021-02-10 09:00:00
2021-02-10 10:00:00
2021-02-10 11:00:00
2021-02-10 12:00:00
2021-02-10 13:00:00
2021-02-10 14:00:00
2021-02-10 15:00:00
2021-02-10 16:00:00
2021-02-10 17:00:00
2021-02-10 18:00:00
2021-02-10 19:00:00
2021-02-10 20:00:00
2021-02-10 21:00:00
2021-02-10 22:00:00
2021-02-10 23:00:00
2021-02-11 00:00:00
2021-02-11 01:00:00
2021-02-11 02:00:00
2021-02-11 03:00:00
2021-02-11 04:00:00
2021-02-11 05:00:00
2021-02-11 06:00:00
2021-02-11 07:00:00
2021-02-11 08:00:00
2021-02-11 09:00:00
2021-02-11 10:00:00
2021-02-11 11:00:00
2021-02-11 12:00:00
2021-02-11 13:00:00
2021-02-11 14:00:00

In [ ]:
train_data[''].value_counts()

In [9]:
doc.describe()

,Unnamed: 0,electric_test.num,electric_test.hh24,electric_test.stn,electric_test.nph_ta,electric_test.nph_hm,electric_test.nph_ws_10m,electric_test.nph_rn_60m,electric_test.nph_ta_chi,electric_test.weekday,electric_test.week_name
count,2.838239e+06,2.838239e+06,2.838239e+06,2.838239e+06,2.838239e+06,2.838239e+06,2.838239e+06,2.838239e+06,2.838239e+06,2.838239e+06,2.838239e+06
mean,1.419120e+06,1.525104e+04,1.250000e+01,4.830708e+02,1.465222e+01,7.163156e+01,1.840850e+00,1.487752e-01,1.442934e+01,3.007535e+00,2.875572e-01
std,8.193292e+05,3.449973e+03,6.922188e+00,2.600145e+02,9.177797e+00,2.034626e+01,1.725482e+00,1.259154e+00,1.165910e+01,2.003408e+00,4.526236e-01
min,1.000000e+00,2.385000e+03,1.000000e+00,9.800000e+01,-2.070000e+01,5.400000e+00,-9.900000e+01,-9.900000e+01,-2.650000e+01,0.000000e+00,0.000000e+00
25%,7.095605e+05,1.232200e+04,6.500000e+00,2.590000e+02,7.700000e+00,5.780000e+01,6.000000e-01,0.000000e+00,4.800000e+00,1.000000e+00,0.000000e+00
50%,1.419120e+06,1.586200e+04,1.200000e+01,4.430000e+02,1.550000e+01,7.520000e+01,1.400000e+00,0.000000e+00,1.560000e+01,3.000000e+00,0.000000e+00
75%,2.128680e+06,1.838650e+04,1.850000e+01,6.490000e+02,2.230000e+01,8.910000e+01,2.500000e+00,0.000000e+00,2.480000e+01,5.000000e+00,1.000000e+00
max,2.838239e+06,2.094700e+04,2.400000e+01,9.910000e+02,3.630000e+01,1.065000e+02,3.000000e+01,1.905000e+02,3.730000e+01,6.000000e+00,1.000000e+00

In [10]:
doc.corr(numeric_only=True)

,Unnamed: 0,electric_test.num,electric_test.hh24,electric_test.stn,electric_test.nph_ta,electric_test.nph_hm,electric_test.nph_ws_10m,electric_test.nph_rn_60m,electric_test.nph_ta_chi,electric_test.weekday,electric_test.week_name
Unnamed: 0,1.000000,-3.382115e-01,8.241229e-06,2.130137e-01,0.087516,0.035932,0.115148,-0.005511,0.035000,3.660851e-05,2.382511e-05
electric_test.num,-0.338212,1.000000e+00,2.548749e-07,-2.295161e-01,-0.061100,-0.139801,-0.217311,0.023836,-0.068012,-1.971734e-07,-2.490834e-07
electric_test.hh24,0.000008,2.548749e-07,1.000000e+00,-3.663887e-07,0.082602,-0.130710,0.042410,-0.013699,0.092542,-5.678640e-04,-4.188539e-04
electric_test.stn,0.213014,-2.295161e-01,-3.663887e-07,1.000000e+00,0.029384,0.010095,-0.006097,-0.001957,0.025024,2.834415e-07,3.580633e-07
electric_test.nph_ta,0.087516,-6.110002e-02,8.260207e-02,2.938386e-02,1.000000,0.323029,0.005918,0.067371,0.951392,-1.054466e-02,-2.224705e-02
electric_test.nph_hm,0.035932,-1.398006e-01,-1.307100e-01,1.009497e-02,0.323029,1.000000,-0.114973,0.136212,0.399559,3.393998e-02,9.009584e-03
electric_test.nph_ws_10m,0.115148,-2.173111e-01,4.241045e-02,-6.096598e-03,0.005918,-0.114973,1.000000,0.077007,-0.058460,7.720632e-03,2.381404e-04
electric_test.nph_rn_60m,-0.005511,2.383603e-02,-1.369916e-02,-1.956818e-03,0.067371,0.136212,0.077007,1.000000,0.077186,-2.025641e-03,-2.592642e-02
electric_test.nph_ta_chi,0.035000,-6.801250e-02,9.254209e-02,2.502388e-02,0.951392,0.399559,-0.058460,0.077186,1.000000,-9.248528e-03,-1.600658e-02
electric_test.weekday,0.000037,-1.971734e-07,-5.678640e-04,2.834415e-07,-0.010545,0.033940,0.007721,-0.002026,-0.009249,1.000000e+00,7.918476e-01
electric_test.week_name,0.000024,-2.490834e-07,-4.188539e-04,3.580633e-07,-0.022247,0.009010,0.000238,-0.025926,-0.016007,7.918476e-01,1.000000e+00

In [20]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(2838239, 12))
sns.heatmap(data = doc.corr(), annot=True, fmt = '.2f', linewidths=0.5, cmap='Blues')

ValueError: could not convert string to float: '2023-01-01 01:00:00'

Error in callback <function _draw_all_if_interactive at 0x000001328B129E40> (for post_execute), with arguments args (),kwargs {}:

ValueError: Image size of 283823900x1200 pixels is too large. It must be less than 2^16 in each direction.